import numpy as np
a = np.arange(9,dtype=np.float64).reshape(3,3)
print("first array:")
print(a)
print("\n")
b = np.array([10,10,10])
print("second array:")
print(b)
print("\n")
print("Array after adding two arrays:")
print(np.add(a,b))
print("\nArray after subtracting two arrays:")
print(np.subtract(a,b))
print("\nArray after multiplying two arrays:")
print(np.multiply(a,b))
print("\nArray after dividing two arrays:")
print(np.divide(a,b))