from tkinter import *
root = Tk()
root.title("main")
root.geometry("400x300")
def topwin():
    top = Toplevel()
    top.title("top")
    top.geometry("200x150")
    l2 = Label(top, text="This is a top window")
    l2.pack()
l = Label(root, text="This is the main window")
btn = Button(root, text="click here to open another window", command=topwin)
l.pack()
btn.pack()
root.mainloop()